Fall 2021 strategic priorities update
natcap/softwareteam pull request #110
Opened 2021-09-10 19:21 UTC by phargogh

Hey everyone,

Here's the updates to our strategic priorities based on the conversations we've had so far.  I added a bit of text to each legitimating _why_ each priority is strategic, so I'd be particularly interested to hear your thoughts on those additions.

I also fleshed out the "what we're working on" and "on deck" sections to include links to relevant resources on github where possible, which also led to the creation of a few new issues for work that I hadn't yet added to the tracker:

* https://github.com/natcap/softwareteam/issues/109
* https://github.com/natcap/softwareteam/issues/108

2021-09-10 20:29 UTC, emlys reviewed
This looks great James!

From the first two priorities it sounds like we're converging on the idea that InVEST is explicitly _not_ designed for users outside of research (an anti-priority?) If that is what we intend, can we include that in this document or another place?

A related but different distinction is "users that have the GIS skills to prepare inputs and analyze outputs". IMO InVEST is pretty explicitly _not_ designed for users that _don't_ have those skills, and that's for the best. But we are working on things (improving guidance about inputs, possible output viewer integrated into the workbench) that may lower the GIS skills barrier. I think that's worthwhile, but we could also be explicit about this dimension of the target user base to set boundaries on how much we need to lower that barrier.

2021-09-10 20:29 UTC, emlys commented on README.md
> +   2. Maintaining data-access APIs as an endpoint of these workflows
```suggestion
   2. Creating and maintaining data-access APIs as an endpoint of these workflows
```
Just to be explicit about this since these APIs don't exist yet

2021-09-13 13:21 UTC, dcdenu4 commented on README.md
> +      Services analyses with a focus on InVEST, pygeoprocessing and taskgraph.
```suggestion
      Services analyses with a focus on InVEST, pygeoprocessing, and taskgraph.
```

2021-09-13 13:48 UTC, dcdenu4 commented
Some thoughts in response to Emily's comments.

>From the first two priorities it sounds like we're converging on the idea that InVEST is explicitly not designed for users outside of research

I'm not sure I'd 100% agree with this, but it mostly depends on the definition of "research". The user group that comes to mind for me is planners / municipalities who have some GIS in house that allow for running InVEST in a useful way. This in house expertise could come from NatCap training, where they build capacity to run InVEST for planning. I wouldn't consider that research per se... I guess it's similar to how NatCap partners with groups to run InVEST on their region to better inform decisions. It feels like a grey area to me and thus leaves me uncomfortable saying InVEST is not designed for users outside of research. 

>A related but different distinction is "users that have the GIS skills to prepare inputs and analyze outputs". IMO InVEST is pretty explicitly not designed for users that don't have those skills

I'm in agreement here.

>...set boundaries on how much we will work to lower that barrier.

I agree that it's good to evaluate what our returns are or will be on a given investment. I'm not sure how or if it is necessary to work this into the strategic goals though. This to me feels like a step in deciding if a project is projected to have enough return under said strategic goal. I'd be curious to hear more of what you're thinking here Emily.

2021-09-13 13:57 UTC, dcdenu4 requested changes
@phargogh this looks pretty well written to me. 

The only thing I feel is missing, which might not belong in this document, is discussion around monitoring. I'd love to try and have a plan for monitoring how our projects currently in transit impact these priority goals. It could go a long way to helping answer Emily's point about return on investment. How can we measure if translating InVEST to Chinese has a noticeable impact? Maybe the launch of the Workbench increases our users by 50%... This is probably a separate discussion.

Oh I had one suggestion in defense of the Oxford comma!

2021-09-13 20:44 UTC, davemfish commented
> Some thoughts in response to Emily's comments.
> 
> > From the first two priorities it sounds like we're converging on the idea that InVEST is explicitly not designed for users outside of research
> 
> I'm not sure I'd 100% agree with this, but it mostly depends on the definition of "research". The user group that comes to mind for me is planners / municipalities who have some GIS in house that allow for running InVEST in a useful way.

I don't really read this as being exclusionary either. The second priority reads "**Expand the user base of InVEST to include more of the research and modeling community**" so I feel like "research & modeling" together capture everyone who might be doing more academic-style "research" and also people who are doing applied modeling in a decision context. It leaves out people who just need to consume information - as opposed to generate it - and those people are the target audience for priority 1.

2021-09-13 20:44 UTC, davemfish approved these changes
Thanks, James!

2021-09-14 01:55 UTC, phargogh commented
Thanks for the comments and feedback, all!

> @emlys  From the first two priorities it sounds like we're converging on the idea that InVEST is explicitly not designed for users outside of research (an anti-priority?) If that is what we intend, can we include that in this document or another place?

I do think it's a fair point that InVEST is likely used in a research-centric context, but this is not to say that InVEST was designed with this in mind.  There has always been the desire for others to take these models and apply them to their own unique use cases, and individual models have typically been designed within particular decision contexts.  But these assumptions and our prior plans at working towards them is not documented anywhere, and I'm starting to think it might be helpful to create an InVEST roadmap.  So here's an issue for starting one: https://github.com/natcap/softwareteam/issues/111

>  @emlys A related but different distinction is "users that have the GIS skills to prepare inputs and analyze outputs". IMO InVEST is pretty explicitly not designed for users that don't have those skills, and that's for the best.

I agree that InVEST _at the moment_ requires strong GIS skills to prepare inputs and analyze outputs, but not necessarily that InVEST was designed this way.  Part of the problem here is that it's mighty difficult to define a general-case solution to this for the InVEST application without just reproducing the functionality of a desktop GIS software.  So instead, we've tended to focus on those parts of the InVEST application that _are_ generalizeable, and this has generally required GIS skills of the user.

I think a part of an InVEST roadmap should include how we can help address bottlenecks to using the InVEST application while still serving the needs of the InVEST library.  Historically the Data Platform was intended to serve this purpose (at least on the data-preparation side), but we should revisit that and see about funding.

> @emlys But we are working on things (improving guidance about inputs, possible output viewer integrated into the workbench) that may lower the GIS skills barrier. I think that's worthwhile, but we could also be explicit about this dimension of the target user base to set boundaries on how much we will work to lower that barrier.

Sounds great to me to be explicit about this!  I'm also open about how best to set/quantify that limit.

> @dcdenu4 The only thing I feel is missing, which might not belong in this document, is discussion around monitoring. I'd love to try and have a plan for monitoring how our projects currently in transit impact these priority goals.

I agree that monitoring progress against our goals would be wise, at least to demonstrate that our work has been making a difference along some measurable dimension.  I've created https://github.com/natcap/softwareteam/issues/112 for some follow-up discussion.

2021-09-14 14:10 UTC, davemfish approved these changes

2021-09-14 17:11 UTC, phargogh commented
FYI, I just created a new issue for creating a cookbook (https://github.com/natcap/softwareteam/issues/113) and added starting the cookbook to the "What we're working on" list in the document pushed here.

2021-09-14 17:12 UTC, emlys approved these changes
@davemfish and @dcdenu4, you make good points about that we still want to support non-academic users. Since we're adding a priority and not dropping any I guess I'm thinking how to balance that with priority 1. Like, given our limited amount of software team time, how much of that should we put into creating new data APIs vs improving documentation so more users can create that data themselves? But we don't have to decide that in this doc.

2021-09-14 19:13 UTC, phargogh commented
> @emlys given our limited amount of software team time, how much of that should we put into creating new data APIs vs improving documentation so more users can create that data themselves?  But we don't have to decide that in this doc.

Yeah, this is an important question, and something that's for sure dependent on a variety of factors that are constantly in flux ... funding, deliverables on sponsored projects and shifting organizational priorities are a few that come to mind.  For the scope of this document, I think the main objective is to highlight which areas/characteristics of our work we think have the greatest leverage.  This can help us make decisions around what work to prioritize when there is a choice to be made.

Commonly, a strategy such as this will define what we believe is most important, and then a more granular and specific plan will outline shorter-term objectives to work towards the strategy.  In this case, we have a (brief) take on such a plan with the "what we're working on" section of this doc, and the aim to refresh it each quarter. I realize that doesn't quite get at the question of "how much time should we spend on each of these?" question, but I'm hoping that the strategic objectives we aim for will make sense in the context of each of the projects.  Does that help?

2021-09-14 19:28 UTC, emlys commented
@phargogh thanks, that makes sense.

2021-09-14 19:53 UTC, phargogh commented
OK!  Well, with that, let's continue discussing and revising this document as needed, and of course continue discussing the other elements that have spun off of this discussion into other issues.  Since we have 3 approvals, I'll merge.

2021-09-14 19:53 UTC, merged